### ISSUE TITLE
Cannot start project

### ISSUE THREAD

**Issue by jonathantneal** [t7/react-ui#22]
Steps to reproduce:

1. Clone the project.
2. Run `npm install`.
3. See failure log.

```
npm install

> fsevents@1.2.7 install ~/GitHub/t7/react-ui/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "~/GitHub/t7/react-ui/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote

> husky@1.3.1 install ~/GitHub/t7/react-ui/node_modules/husky
> node husky install

husky > setting up git hooks
husky > done

> @0.0.1 postinstall ~/GitHub/t7/react-ui
> npm run bootstrap


> @0.0.1 bootstrap ~/GitHub/t7/react-ui
> lerna bootstrap

lerna notice cli v3.13.1
lerna info versioning independent
lerna info Bootstrapping 8 packages
lerna info Symlinking packages and binaries
lerna info lifecycle @t7/paging@0.0.3~prepublish: @t7/paging@0.0.3

> @t7/paging@0.0.3 prepublish ~/GitHub/t7/react-ui/packages/paging
> npm run build


> @t7/paging@0.0.3 build ~/GitHub/t7/react-ui/packages/paging
> webpack --config ../../webpack.config.js

~/GitHub/t7/react-ui/packages/paging/node_modules/webpack-cli/bin/cli.js:231
                                throw err;
                                ^

TypeError: acorn.Parser.extend is not a function
    at Object.<anonymous> (~/GitHub/t7/react-ui/packages/paging/node_modules/webpack/lib/Parser.js:18:34)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (~/GitHub/t7/react-ui/packages/paging/node_modules/webpack/lib/JavascriptModulesPlugin.js:7:16)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (~/GitHub/t7/react-ui/packages/paging/node_modules/webpack/lib/WebpackOptionsApply.js:9:33)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (~/GitHub/t7/react-ui/packages/paging/node_modules/webpack/lib/webpack.js:10:29)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @t7/paging@0.0.3 build: `webpack --config ../../webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @t7/paging@0.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-03-13T18_10_21_043Z-debug.log
lerna info lifecycle @t7/paging@0.0.3~prepublish: Failed to exec prepublish script
lerna ERR! lifecycle "prepublish" errored in "@t7/paging", exiting 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.0.1 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @0.0.1 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-03-13T18_10_21_087Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.0.1 postinstall: `npm run bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-03-13T18_10_21_174Z-debug.log
```

**Comment by gr8fuljoe5** [comment]
Did you try deleting your `node_modules` folder before install?

**Comment by gr8fuljoe5** [comment]
```
| => node -v; npm -v
v8.6.0
5.3.0
```

**Comment by gr8fuljoe5** [comment]
So I'd run this: `rm -rf node_modules && npm install --package-lock && npm run dev`

**Comment by jonathantneal** [comment]
Possibly related issue: https://bugs.archlinux.org/task/60610

**Comment by jonathantneal** [comment]
After running [@gr8fuljoe5’s recommendation](https://github.com/t7/react-ui/issues/22#issuecomment-472847490):

```
rm -rf node_modules && npm install --package-lock

> fsevents@1.2.7 install ~/GitHub/t7/react-ui/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "~/GitHub/t7/react-ui/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote

> husky@1.3.1 install ~/GitHub/t7/react-ui/node_modules/husky
> node husky install

husky > setting up git hooks
husky > done

> webpack-cli@3.2.1 postinstall ~/GitHub/t7/react-ui/node_modules/webpack-cli
> lightercollective


     *** Thank you for using webpack-cli! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/webpack/donate

                    ***


> @0.0.1 postinstall ~/GitHub/t7/react-ui
> npm run bootstrap


> @0.0.1 bootstrap ~/GitHub/t7/react-ui
> lerna bootstrap

lerna notice cli v3.10.7
lerna info versioning independent
lerna info Bootstrapping 8 packages
lerna info Symlinking packages and binaries
lerna info lifecycle @t7/paging@0.0.3~prepublish: @t7/paging@0.0.3

> @t7/paging@0.0.3 prepublish ~/GitHub/t7/react-ui/packages/paging
> npm run build


> @t7/paging@0.0.3 build ~/GitHub/t7/react-ui/packages/paging
> webpack --config ../../webpack.config.js

~/GitHub/t7/react-ui/packages/paging/node_modules/@xtuc/ieee754/index.js:1
(function (exports, require, module, __filename, __dirname) { export function read(buffer, offset, isLE, mLen, nBytes) {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:85:7)
    at NativeCompileCache._moduleCompile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (~/GitHub/t7/react-ui/packages/paging/node_modules/@webassemblyjs/ieee754/lib/index.js:12:13)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (~/GitHub/t7/react-ui/packages/paging/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:10:39)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (~/GitHub/t7/react-ui/packages/paging/node_modules/@webassemblyjs/wasm-parser/lib/index.js:8:39)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @t7/paging@0.0.3 build: `webpack --config ../../webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @t7/paging@0.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-03-14T13_18_48_856Z-debug.log
lerna info lifecycle @t7/paging@0.0.3~prepublish: Failed to exec prepublish script
lerna ERR! lifecycle "prepublish" errored in "@t7/paging", exiting 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.0.1 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @0.0.1 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-03-14T13_18_48_980Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.0.1 postinstall: `npm run bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-03-14T13_18_49_102Z-debug.log
```

**Comment by jonathantneal** [comment]
I tried this again tonight. I believe the error is the same.

```
➜  react-ui git:(master) npm install

> @0.0.1 postinstall ~/GitHub/t7/react-ui
> npm run bootstrap


> @0.0.1 bootstrap ~/GitHub/t7/react-ui
> lerna bootstrap

lerna notice cli v3.13.1
lerna info versioning independent
lerna info Bootstrapping 8 packages
lerna info Symlinking packages and binaries
lerna info lifecycle @t7/paging@0.0.3~prepublish: @t7/paging@0.0.3

> @t7/paging@0.0.3 prepublish ~/GitHub/t7/react-ui/packages/paging
> npm run build


> @t7/paging@0.0.3 build ~/GitHub/t7/react-ui/packages/paging
> webpack --config ../../webpack.config.js

~/GitHub/t7/react-ui/packages/paging/node_modules/webpack-cli/bin/cli.js:231
                                throw err;
                                ^

TypeError: acorn.Parser.extend is not a function
    at Object.<anonymous> (~/GitHub/t7/react-ui/packages/paging/node_modules/webpack/lib/Parser.js:18:34)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (~/GitHub/t7/react-ui/packages/paging/node_modules/webpack/lib/JavascriptModulesPlugin.js:7:16)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (~/GitHub/t7/react-ui/packages/paging/node_modules/webpack/lib/WebpackOptionsApply.js:9:33)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (~/GitHub/t7/react-ui/packages/paging/node_modules/webpack/lib/webpack.js:10:29)
    at Module._compile (~/GitHub/t7/react-ui/packages/paging/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @t7/paging@0.0.3 build: `webpack --config ../../webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @t7/paging@0.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-03-30T05_31_33_028Z-debug.log
lerna info lifecycle @t7/paging@0.0.3~prepublish: Failed to exec prepublish script
lerna ERR! lifecycle "prepublish" errored in "@t7/paging", exiting 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.0.1 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @0.0.1 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-03-30T05_31_33_068Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.0.1 postinstall: `npm run bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2019-03-30T05_31_33_099Z-debug.log
➜  react-ui git:(master)
```
